const { PrismaClient } = require("@prisma/client");
const bcrypt = require("bcryptjs");

const prisma = new PrismaClient();

async function main() {
  // Create Admin User
  const adminPassword = await bcrypt.hash("admin123", 12);
  const admin = await prisma.user.upsert({
    where: { email: "admin@fundamentalgrow.com" },
    update: {},
    create: {
      name: "Admin",
      email: "admin@fundamentalgrow.com",
      password: adminPassword,
      role: "ADMIN",
    },
  });
  console.log("✅ Admin created:", admin.email);

  // Create Test Users
  const userPassword = await bcrypt.hash("user123", 12);
  const testUsers = [
    { name: "Rahul Sharma", email: "rahul.sharma@gmail.com" },
    { name: "Priya Patel", email: "priya.patel@gmail.com" },
    { name: "Amit Kumar", email: "amit.kumar@gmail.com" },
    { name: "Neha Singh", email: "neha.singh@gmail.com" },
    { name: "Vikram Desai", email: "vikram.desai@gmail.com" },
    { name: "Anjali Verma", email: "anjali.verma@gmail.com" },
    { name: "Suresh Reddy", email: "suresh.reddy@gmail.com" },
    { name: "Kavita Nair", email: "kavita.nair@gmail.com" },
    { name: "Rajesh Gupta", email: "rajesh.gupta@gmail.com" },
    { name: "Meera Iyer", email: "meera.iyer@gmail.com" },
    { name: "Arjun Malhotra", email: "arjun.malhotra@gmail.com" },
    { name: "Deepika Joshi", email: "deepika.joshi@gmail.com" },
  ];

  const users = [admin];
  for (const u of testUsers) {
    const user = await prisma.user.upsert({
      where: { email: u.email },
      update: {},
      create: { ...u, password: userPassword, role: "USER" },
    });
    users.push(user);
  }
  console.log("✅ Users created:", users.length);

  // Create Campaigns (amounts converted to paise)
  const campaigns = [
    {
      title: "Education for Underprivileged Children",
      slug: "education-for-underprivileged-children",
      description:
        "Help us provide quality education to 500+ children in rural areas. Your donation will cover books, uniforms, and school supplies for an entire year.",
      story:
        "In rural Maharashtra, thousands of children are deprived of basic education due to lack of resources. Many families cannot afford books, uniforms, or even basic school supplies. Our foundation has been working for 5 years to bridge this gap. We have already helped 2000+ children get access to quality education. This campaign aims to reach 500 more children in remote villages.",
      image:
        "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=800&q=80",
      goalAmount: 500000 * 100,
      raisedAmount: 325000 * 100,
      category: "Education",
      location: "Maharashtra",
      organizerName: "Shiksha Foundation",
      organizerEmail: "contact@shiksha.org",
      organizerPhone: "9876543210",
      status: "active",
      featured: true,
      isPublic: true,
      endDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
    },
    {
      title: "Digital Literacy for Rural Youth",
      slug: "digital-literacy-rural-youth",
      description:
        "Empower rural youth with computer skills and internet access. Help bridge the digital divide.",
      story:
        "In today's digital age, computer literacy is essential. However, millions of rural youth lack access to computers and the internet. Our program aims to set up 10 computer labs in remote villages, each equipped with 20 computers and high-speed internet. We provide free training in basic computer skills, MS Office, and internet usage.",
      image:
        "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
      goalAmount: 800000 * 100,
      raisedAmount: 456000 * 100,
      category: "Education",
      location: "Bihar",
      organizerName: "Digital India Foundation",
      organizerEmail: "info@digitalindia.org",
      organizerPhone: "9876543220",
      status: "active",
      featured: true,
      isPublic: true,
      endDate: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000),
    },
    {
      title: "Medical Aid for Cancer Patients",
      slug: "medical-aid-for-cancer-patients",
      description:
        "Support cancer patients who cannot afford treatment. Your contribution will help cover chemotherapy, medicines, and hospital expenses.",
      story:
        "Cancer treatment is expensive and many families in India cannot afford it. We have partnered with leading hospitals to provide subsidized treatment to underprivileged cancer patients. In the past 3 years, we have helped 150+ patients get life-saving treatment.",
      image:
        "https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=800&q=80",
      goalAmount: 1000000 * 100,
      raisedAmount: 750000 * 100,
      category: "Medical",
      location: "Delhi",
      organizerName: "Hope Healthcare Trust",
      organizerEmail: "info@hopehealthcare.org",
      organizerPhone: "9876543211",
      status: "active",
      featured: true,
      isPublic: true,
      endDate: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000),
    },
    {
      title: "Bird Hospital",
      slug: "bird-hospital",
      description: "Save injured birds with our specialized avian hospital.",
      story:
        "From kite string injuries to window collisions, birds face many urban hazards. Our hospital treats over 2000 birds annually including pigeons, kites, owls, and parrots. We provide surgery, rehabilitation, and release services.",
      image:
        "https://images.unsplash.com/photo-1452570053594-1b985d6ea890?w=800&q=80",
      goalAmount: 400000 * 100,
      raisedAmount: 269500 * 100,
      category: "Animal Welfare",
      location: "Ahmedabad",
      organizerName: "Wings of Hope",
      organizerEmail: "birds@wingsofhope.org",
      organizerPhone: "9876543264",
      status: "active",
      featured: false,
      isPublic: true,
      endDate: new Date(Date.now() + 33 * 24 * 60 * 60 * 1000),
    },
    {
      title: "Shelter for Homeless Families",
      slug: "shelter-for-homeless-families",
      description:
        "Help us build temporary shelters for homeless families during winter. Each shelter can accommodate a family of 4.",
      story:
        "Every winter, thousands of homeless families struggle to survive the harsh cold in Uttar Pradesh. Our organization has been providing temporary shelters for the past 7 years. These shelters are equipped with basic amenities like bedding, heating, and sanitation facilities.",
      image:
        "https://images.unsplash.com/photo-1532629345422-7515f3d16bb6?w=800&q=80",
      goalAmount: 450000 * 100,
      raisedAmount: 291000 * 100,
      category: "Humanitarian",
      location: "Uttar Pradesh",
      organizerName: "Aashray Foundation",
      organizerEmail: "aashray@foundation.org",
      organizerPhone: "9876543212",
      status: "active",
      featured: true,
      isPublic: true,
      endDate: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000),
    },
    {
      title: "Women's Skill Training Program",
      slug: "womens-skill-training-program",
      description:
        "Empower women through vocational training and job placement.",
      story:
        "Training women for sustainable livelihoods in textile, handicrafts, and services.",
      image:
        "https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&q=80",
      goalAmount: 600000 * 100,
      raisedAmount: 350000 * 100,
      category: "Skill Development",
      location: "Karnataka",
      organizerName: "Women Empowerment Trust",
      organizerEmail: "women@trust.org",
      organizerPhone: "9876543213",
      status: "active",
      featured: true,
      isPublic: true,
      endDate: new Date(Date.now() + 35 * 24 * 60 * 60 * 1000),
    },
    {
      title: "Child Nutrition Program",
      slug: "child-nutrition-program",
      description: "Combat malnutrition in children through nutrition centers.",
      story:
        "Providing nutritious meals and health checkups to malnourished children.",
      image:
        "https://images.unsplash.com/photo-1494309513473-e97345c2a14a?w=800&q=80",
      goalAmount: 700000 * 100,
      raisedAmount: 420000 * 100,
      category: "Health",
      location: "Chhattisgarh",
      organizerName: "Nutrition Foundation",
      organizerEmail: "nutrition@foundation.org",
      organizerPhone: "9876543214",
      status: "active",
      featured: false,
      isPublic: true,
      endDate: new Date(Date.now() + 40 * 24 * 60 * 60 * 1000),
    },
    {
      title: "Clean Water Project",
      slug: "clean-water-project",
      description:
        "Install water purification systems in villages lacking clean water.",
      story:
        "Providing safe drinking water to 50 villages in drought-affected areas.",
      image:
        "https://images.unsplash.com/photo-1559628233-efc59c8f3f3d?w=800&q=80",
      goalAmount: 900000 * 100,
      raisedAmount: 550000 * 100,
      category: "Environment",
      location: "Rajasthan",
      organizerName: "Pure Water Initiative",
      organizerEmail: "water@initiative.org",
      organizerPhone: "9876543215",
      status: "active",
      featured: true,
      isPublic: true,
      endDate: new Date(Date.now() + 50 * 24 * 60 * 60 * 1000),
    },
    {
      title: "Solar Energy for Villages",
      slug: "solar-energy-villages",
      description:
        "Install solar panels in villages to provide clean energy access.",
      story: "Bringing renewable energy and electricity to off-grid villages.",
      image:
        "https://images.unsplash.com/photo-1509391366360-2e938f4f4c6c?w=800&q=80",
      goalAmount: 1200000 * 100,
      raisedAmount: 700000 * 100,
      category: "Environment",
      location: "Jharkhand",
      organizerName: "Solar Foundation",
      organizerEmail: "solar@foundation.org",
      organizerPhone: "9876543216",
      status: "active",
      featured: true,
      isPublic: true,
      endDate: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000),
    },
    {
      title: "Elderly Care Center",
      slug: "elderly-care-center",
      description: "Build a comprehensive care center for senior citizens.",
      story:
        "Providing shelter, healthcare, and dignified living for abandoned elderly.",
      image:
        "https://images.unsplash.com/photo-1576091160550-112173f7f869?w=800&q=80",
      goalAmount: 800000 * 100,
      raisedAmount: 480000 * 100,
      category: "Senior Care",
      location: "Goa",
      organizerName: "Golden Years Foundation",
      organizerEmail: "elderly@goldenyears.org",
      organizerPhone: "9876543217",
      status: "active",
      featured: false,
      isPublic: true,
      endDate: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000),
    },
    {
      title: "Autism Center",
      slug: "autism-center",
      description: "Support center for children with autism spectrum disorder.",
      story:
        "Therapy, education, and vocational training for autistic children.",
      image:
        "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80",
      goalAmount: 600000 * 100,
      raisedAmount: 360000 * 100,
      category: "Special Care",
      location: "Bangalore",
      organizerName: "Autism Care Trust",
      organizerEmail: "autism@care.org",
      organizerPhone: "9876543218",
      status: "active",
      featured: true,
      isPublic: true,
      endDate: new Date(Date.now() + 38 * 24 * 60 * 60 * 1000),
    },
    {
      title: "Street Dogs Shelter",
      slug: "street-dogs-shelter",
      description: "Build a sanctuary for stray and abandoned dogs.",
      story: "Medical care, food, and adoption services for street dogs.",
      image:
        "https://images.unsplash.com/photo-1552053831-71594a27c62d?w=800&q=80",
      goalAmount: 500000 * 100,
      raisedAmount: 300000 * 100,
      category: "Animal Welfare",
      location: "Punjab",
      organizerName: "Dog Rescue Foundation",
      organizerEmail: "dogs@rescue.org",
      organizerPhone: "9876543219",
      status: "active",
      featured: false,
      isPublic: true,
      endDate: new Date(Date.now() + 42 * 24 * 60 * 60 * 1000),
    },
    {
      title: "Disaster Relief Fund",
      slug: "disaster-relief-fund",
      description: "Emergency relief for people affected by natural disasters.",
      story: "Quick response teams providing food, water, and medical aid.",
      image:
        "https://images.unsplash.com/photo-1548592328-c9fa89d128fa?w=800&q=80",
      goalAmount: 1000000 * 100,
      raisedAmount: 650000 * 100,
      category: "Humanitarian",
      location: "Multi-state",
      organizerName: "Disaster Relief Force",
      organizerEmail: "relief@force.org",
      organizerPhone: "9876543220",
      status: "active",
      featured: true,
      isPublic: true,
      endDate: new Date(Date.now() + 55 * 24 * 60 * 60 * 1000),
    },
    {
      title: "Mental Health Awareness",
      slug: "mental-health-awareness",
      description:
        "Campaign to promote mental health awareness and counseling.",
      story:
        "Free counseling and mental health workshops in schools and communities.",
      image:
        "https://images.unsplash.com/photo-1577720643272-265f434b0b11?w=800&q=80",
      goalAmount: 400000 * 100,
      raisedAmount: 240000 * 100,
      category: "Health",
      location: "Tamil Nadu",
      organizerName: "Mental Wellness Trust",
      organizerEmail: "mental@wellness.org",
      organizerPhone: "9876543221",
      status: "active",
      featured: false,
      isPublic: true,
      endDate: new Date(Date.now() + 35 * 24 * 60 * 60 * 1000),
    },
    {
      title: "School Building Project",
      slug: "school-building-project",
      description: "Construct a new school in a remote village.",
      story: "Building infrastructure for 300 students in an underserved area.",
      image:
        "https://images.unsplash.com/photo-1427504494785-cdaf1ef60515?w=800&q=80",
      goalAmount: 1500000 * 100,
      raisedAmount: 900000 * 100,
      category: "Education",
      location: "Odisha",
      organizerName: "Build Education Foundation",
      organizerEmail: "build@education.org",
      organizerPhone: "9876543222",
      status: "active",
      featured: true,
      isPublic: true,
      endDate: new Date(Date.now() + 70 * 24 * 60 * 60 * 1000),
    },
    {
      title: "Community Garden Initiative",
      slug: "community-garden-initiative",
      description: "Create sustainable community gardens for urban farming.",
      story:
        "Promoting organic farming and sustainable food production in cities.",
      image:
        "https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?w=800&q=80",
      goalAmount: 300000 * 100,
      raisedAmount: 180000 * 100,
      category: "Environment",
      location: "West Bengal",
      organizerName: "Green Growth Initiative",
      organizerEmail: "green@growth.org",
      organizerPhone: "9876543223",
      status: "active",
      featured: false,
      isPublic: true,
      endDate: new Date(Date.now() + 32 * 24 * 60 * 60 * 1000),
    },
    {
      title: "Leprosy Rehabilitation Center",
      slug: "leprosy-rehabilitation-center",
      description: "Support and rehabilitation for leprosy patients.",
      story:
        "Medical treatment and social rehabilitation for affected individuals.",
      image:
        "https://images.unsplash.com/photo-1581092916550-e323be2ae537?w=800&q=80",
      goalAmount: 700000 * 100,
      raisedAmount: 420000 * 100,
      category: "Medical",
      location: "Andhra Pradesh",
      organizerName: "Leprosy Care Foundation",
      organizerEmail: "leprosy@care.org",
      organizerPhone: "9876543224",
      status: "active",
      featured: false,
      isPublic: true,
      endDate: new Date(Date.now() + 48 * 24 * 60 * 60 * 1000),
    },
    {
      title: "Orphanage Support Program",
      slug: "orphanage-support-program",
      description:
        "Provide education, healthcare, and nutrition for orphaned children.",
      story: "Supporting 5 orphanages with 300+ children in different states.",
      image:
        "https://images.unsplash.com/photo-1469571486292-0ba58fe46b35?w=800&q=80",
      goalAmount: 900000 * 100,
      raisedAmount: 540000 * 100,
      category: "Child Welfare",
      location: "Multiple States",
      organizerName: "Orphanage Relief Foundation",
      organizerEmail: "orphan@relief.org",
      organizerPhone: "9876543225",
      status: "active",
      featured: true,
      isPublic: true,
      endDate: new Date(Date.now() + 52 * 24 * 60 * 60 * 1000),
    },
    {
      title: "Sports Academy for Underprivileged",
      slug: "sports-academy-underprivileged",
      description:
        "Sports training and facilities for talented but poor children.",
      story: "Identify and nurture athletic talent from rural backgrounds.",
      image:
        "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=800&q=80",
      goalAmount: 550000 * 100,
      raisedAmount: 330000 * 100,
      category: "Sports",
      location: "Telangana",
      organizerName: "Youth Sports Foundation",
      organizerEmail: "sports@youth.org",
      organizerPhone: "9876543226",
      status: "active",
      featured: false,
      isPublic: true,
      endDate: new Date(Date.now() + 40 * 24 * 60 * 60 * 1000),
    },
    {
      title: "Library Development",
      slug: "library-development",
      description:
        "Establish libraries in villages to promote reading culture.",
      story: "Creating 20 community libraries with diverse book collections.",
      image:
        "https://images.unsplash.com/photo-150784272343-583f20270319?w=800&q=80",
      goalAmount: 400000 * 100,
      raisedAmount: 240000 * 100,
      category: "Education",
      location: "Madhya Pradesh",
      organizerName: "Knowledge Foundation",
      organizerEmail: "library@knowledge.org",
      organizerPhone: "9876543227",
      status: "active",
      featured: false,
      isPublic: true,
      endDate: new Date(Date.now() + 36 * 24 * 60 * 60 * 1000),
    },
    {
      title: "Skill Training for Disabled",
      slug: "skill-training-disabled",
      description: "Vocational training for persons with disabilities.",
      story: "Empowering 500 disabled individuals with marketable skills.",
      image:
        "https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&q=80",
      goalAmount: 600000 * 100,
      raisedAmount: 360000 * 100,
      category: "Skill Development",
      location: "Gujarat",
      organizerName: "Ability Empowerment Trust",
      organizerEmail: "ability@empowerment.org",
      organizerPhone: "9876543228",
      status: "active",
      featured: true,
      isPublic: true,
      endDate: new Date(Date.now() + 44 * 24 * 60 * 60 * 1000),
    },
    {
      title: "Wildlife Conservation",
      slug: "wildlife-conservation",
      description:
        "Protect endangered wildlife species in their natural habitats.",
      story:
        "Conservation efforts for tigers, elephants, and other endangered species.",
      image:
        "https://images.unsplash.com/photo-1446716878081-d282a0f896e2?w=800&q=80",
      goalAmount: 1000000 * 100,
      raisedAmount: 600000 * 100,
      category: "Environment",
      location: "Uttarakhand",
      organizerName: "Wildlife Protection Foundation",
      organizerEmail: "wildlife@protection.org",
      organizerPhone: "9876543229",
      status: "active",
      featured: true,
      isPublic: true,
      endDate: new Date(Date.now() + 65 * 24 * 60 * 60 * 1000),
    },
    {
      title: "Maternal Health Program",
      slug: "maternal-health-program",
      description: "Improve maternal and child health outcomes in rural areas.",
      story: "Free prenatal care and safe delivery services for poor women.",
      image:
        "https://images.unsplash.com/photo-1576091160596-112173f7f869?w=800&q=80",
      goalAmount: 800000 * 100,
      raisedAmount: 480000 * 100,
      category: "Health",
      location: "Assam",
      organizerName: "Mother Care Foundation",
      organizerEmail: "mother@care.org",
      organizerPhone: "9876543230",
      status: "active",
      featured: false,
      isPublic: true,
      endDate: new Date(Date.now() + 50 * 24 * 60 * 60 * 1000),
    },
    {
      title: "Anti-Trafficking Campaign",
      slug: "anti-trafficking-campaign",
      description: "Combat human trafficking and support survivors.",
      story:
        "Rehabilitation and vocational training for trafficking survivors.",
      image:
        "https://images.unsplash.com/photo-1550355291-bbee04a92027?w=800&q=80",
      goalAmount: 700000 * 100,
      raisedAmount: 420000 * 100,
      category: "Humanitarian",
      location: "West Bengal",
      organizerName: "Freedom Foundation",
      organizerEmail: "freedom@foundation.org",
      organizerPhone: "9876543231",
      status: "active",
      featured: true,
      isPublic: true,
      endDate: new Date(Date.now() + 48 * 24 * 60 * 60 * 1000),
    },
    {
      title: "Flood Relief Initiative",
      slug: "flood-relief-initiative",
      description: "Emergency aid for flood-affected communities.",
      story: "Providing immediate relief and rehabilitation services.",
      image:
        "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80",
      goalAmount: 900000 * 100,
      raisedAmount: 540000 * 100,
      category: "Humanitarian",
      location: "Kerala",
      organizerName: "Flood Relief Trust",
      organizerEmail: "flood@relief.org",
      organizerPhone: "9876543232",
      status: "active",
      featured: false,
      isPublic: true,
      endDate: new Date(Date.now() + 42 * 24 * 60 * 60 * 1000),
    },
    {
      title: "Arts & Culture Preservation",
      slug: "arts-culture-preservation",
      description:
        "Preserve traditional arts and crafts of indigenous communities.",
      story: "Supporting artisans and promoting cultural heritage.",
      image:
        "https://images.unsplash.com/photo-1579783902614-e3fb5141b0cb?w=800&q=80",
      goalAmount: 500000 * 100,
      raisedAmount: 300000 * 100,
      category: "Culture",
      location: "Rajasthan",
      organizerName: "Cultural Heritage Foundation",
      organizerEmail: "culture@heritage.org",
      organizerPhone: "9876543233",
      status: "active",
      featured: false,
      isPublic: true,
      endDate: new Date(Date.now() + 38 * 24 * 60 * 60 * 1000),
    },
    {
      title: "Rural Veterinary Clinic",
      slug: "rural-veterinary-clinic",
      description: "Free veterinary services for livestock in rural areas.",
      story: "Healthcare for cattle, buffalo, and other farm animals.",
      image:
        "https://images.unsplash.com/photo-1576091160399-112c9e29546f?w=800&q=80",
      goalAmount: 400000 * 100,
      raisedAmount: 240000 * 100,
      category: "Animal Welfare",
      location: "Haryana",
      organizerName: "Rural Vet Foundation",
      organizerEmail: "rural@vet.org",
      organizerPhone: "9876543234",
      status: "active",
      featured: false,
      isPublic: true,
      endDate: new Date(Date.now() + 35 * 24 * 60 * 60 * 1000),
    },
    {
      title: "Student Scholarship Fund",
      slug: "student-scholarship-fund",
      description:
        "Scholarships for meritorious but economically weak students.",
      story: "Supporting 100 students pursuing higher education.",
      image:
        "https://images.unsplash.com/photo-1427504494785-cdaf1ef60515?w=800&q=80",
      goalAmount: 1000000 * 100,
      raisedAmount: 600000 * 100,
      category: "Education",
      location: "Uttar Pradesh",
      organizerName: "Scholarship Foundation",
      organizerEmail: "scholarship@fund.org",
      organizerPhone: "9876543235",
      status: "active",
      featured: true,
      isPublic: true,
      endDate: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000),
    },
    {
      title: "Tuberculosis Control Program",
      slug: "tuberculosis-control-program",
      description: "Free screening and treatment for tuberculosis patients.",
      story: "Comprehensive TB control and prevention in high-risk areas.",
      image:
        "https://images.unsplash.com/photo-1530497610245-94d3c16cda28?w=800&q=80",
      goalAmount: 600000 * 100,
      raisedAmount: 360000 * 100,
      category: "Medical",
      location: "Bihar",
      organizerName: "TB Control Trust",
      organizerEmail: "tb@control.org",
      organizerPhone: "9876543236",
      status: "active",
      featured: false,
      isPublic: true,
      endDate: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000),
    },
    {
      title: "Waste Management Project",
      slug: "waste-management-project",
      description: "Implement waste segregation and recycling in communities.",
      story: "Creating 50 waste management centers with training programs.",
      image:
        "https://images.unsplash.com/photo-1559734876-a5c2e6aa8373?w=800&q=80",
      goalAmount: 700000 * 100,
      raisedAmount: 420000 * 100,
      category: "Environment",
      location: "Mumbai",
      organizerName: "Waste Management Initiative",
      organizerEmail: "waste@management.org",
      organizerPhone: "9876543237",
      status: "active",
      featured: true,
      isPublic: true,
      endDate: new Date(Date.now() + 52 * 24 * 60 * 60 * 1000),
    },
    {
      title: "Dental Care Camp",
      slug: "dental-care-camp",
      description: "Free dental checkup and treatment for poor children.",
      story: "Mobile dental clinics visiting 30 villages per month.",
      image:
        "https://images.unsplash.com/photo-1606811841689-23dfddce3e95?w=800&q=80",
      goalAmount: 300000 * 100,
      raisedAmount: 180000 * 100,
      category: "Health",
      location: "Jharkhand",
      organizerName: "Dental Care Trust",
      organizerEmail: "dental@care.org",
      organizerPhone: "9876543238",
      status: "active",
      featured: false,
      isPublic: true,
      endDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
    },
    {
      title: "Women's Microfinance Program",
      slug: "womens-microfinance-program",
      description:
        "Microloans for women entrepreneurs to start small businesses.",
      story: "Empowering 200 women to become self-employed.",
      image:
        "https://images.unsplash.com/photo-1573496359142-b8d87734a5a0?w=800&q=80",
      goalAmount: 800000 * 100,
      raisedAmount: 480000 * 100,
      category: "Economic Empowerment",
      location: "Andhra Pradesh",
      organizerName: "Microfinance Trust",
      organizerEmail: "micro@finance.org",
      organizerPhone: "9876543239",
      status: "active",
      featured: true,
      isPublic: true,
      endDate: new Date(Date.now() + 55 * 24 * 60 * 60 * 1000),
    },
    {
      title: "Street School Initiative",
      slug: "street-school-initiative",
      description: "Education for children of street dwellers and homeless.",
      story:
        "Informal schools providing basic education to marginalized children.",
      image:
        "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=800&q=80",
      goalAmount: 500000 * 100,
      raisedAmount: 300000 * 100,
      category: "Education",
      location: "Delhi",
      organizerName: "Street Children Foundation",
      organizerEmail: "street@children.org",
      organizerPhone: "9876543240",
      status: "active",
      featured: false,
      isPublic: true,
      endDate: new Date(Date.now() + 40 * 24 * 60 * 60 * 1000),
    },
    {
      title: "Hearing Impaired Support",
      slug: "hearing-impaired-support",
      description: "Hearing aids and speech therapy for deaf children.",
      story: "Providing assistive devices and rehabilitation services.",
      image:
        "https://images.unsplash.com/photo-1516585427167-9f4af9627e6c?w=800&q=80",
      goalAmount: 600000 * 100,
      raisedAmount: 360000 * 100,
      category: "Special Care",
      location: "Bangalore",
      organizerName: "Hear Well Foundation",
      organizerEmail: "hear@well.org",
      organizerPhone: "9876543241",
      status: "active",
      featured: false,
      isPublic: true,
      endDate: new Date(Date.now() + 48 * 24 * 60 * 60 * 1000),
    },
    {
      title: "Renewable Energy Training",
      slug: "renewable-energy-training",
      description: "Vocational training in renewable energy technologies.",
      story: "Training 300 youth in solar installation and maintenance.",
      image:
        "https://images.unsplash.com/photo-1509391366360-2e938f4f4c6c?w=800&q=80",
      goalAmount: 700000 * 100,
      raisedAmount: 420000 * 100,
      category: "Skill Development",
      location: "Tamil Nadu",
      organizerName: "Energy Skills Foundation",
      organizerEmail: "energy@skills.org",
      organizerPhone: "9876543242",
      status: "active",
      featured: true,
      isPublic: true,
      endDate: new Date(Date.now() + 50 * 24 * 60 * 60 * 1000),
    },
    {
      title: "Migrant Worker Support",
      slug: "migrant-worker-support",
      description: "Support services for migrant workers and their families.",
      story: "Legal aid, healthcare, and financial literacy programs.",
      image:
        "https://images.unsplash.com/photo-1536849460588-696219a9e98d?w=800&q=80",
      goalAmount: 600000 * 100,
      raisedAmount: 360000 * 100,
      category: "Labor Welfare",
      location: "Maharashtra",
      organizerName: "Migrant Care Foundation",
      organizerEmail: "migrant@care.org",
      organizerPhone: "9876543243",
      status: "active",
      featured: false,
      isPublic: true,
      endDate: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000),
    },
    {
      title: "Eye Care Initiative",
      slug: "eye-care-initiative",
      description: "Free eye checkups and spectacles for poor people.",
      story: "Mobile eye clinics and cataract surgery camps.",
      image:
        "https://images.unsplash.com/photo-1576091160550-112173f7f869?w=800&q=80",
      goalAmount: 500000 * 100,
      raisedAmount: 300000 * 100,
      category: "Health",
      location: "Andhra Pradesh",
      organizerName: "Eye Care Trust",
      organizerEmail: "eye@care.org",
      organizerPhone: "9876543244",
      status: "active",
      featured: false,
      isPublic: true,
      endDate: new Date(Date.now() + 42 * 24 * 60 * 60 * 1000),
    },
    {
      title: "Agricultural Training Centers",
      slug: "agricultural-training-centers",
      description: "Training farmers in modern and sustainable agriculture.",
      story: "Helping 500 farmers increase crop yield and income.",
      image:
        "https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=800&q=80",
      goalAmount: 700000 * 100,
      raisedAmount: 420000 * 100,
      category: "Agriculture",
      location: "Punjab",
      organizerName: "Farmer Development Foundation",
      organizerEmail: "farmer@development.org",
      organizerPhone: "9876543245",
      status: "active",
      featured: true,
      isPublic: true,
      endDate: new Date(Date.now() + 58 * 24 * 60 * 60 * 1000),
    },
    {
      title: "Transgender Support Program",
      slug: "transgender-support-program",
      description:
        "Health, education, and livelihood support for transgender individuals.",
      story: "Comprehensive support and social reintegration services.",
      image:
        "https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&q=80",
      goalAmount: 500000 * 100,
      raisedAmount: 300000 * 100,
      category: "Social Welfare",
      location: "Karnataka",
      organizerName: "Transgender Rights Foundation",
      organizerEmail: "transgender@rights.org",
      organizerPhone: "9876543246",
      status: "active",
      featured: false,
      isPublic: true,
      endDate: new Date(Date.now() + 40 * 24 * 60 * 60 * 1000),
    },
    {
      title: "Digital Literacy for Seniors",
      slug: "digital-literacy-seniors",
      description: "Teaching basic computer and internet skills to elderly.",
      story: "Helping 1000 seniors connect with family online safely.",
      image:
        "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
      goalAmount: 400000 * 100,
      raisedAmount: 240000 * 100,
      category: "Education",
      location: "Goa",
      organizerName: "Senior Tech Foundation",
      organizerEmail: "senior@tech.org",
      organizerPhone: "9876543247",
      status: "active",
      featured: false,
      isPublic: true,
      endDate: new Date(Date.now() + 35 * 24 * 60 * 60 * 1000),
    },
    {
      title: "Foodbank Network",
      slug: "foodbank-network",
      description:
        "Collect and distribute surplus food to prevent waste and hunger.",
      story: "Feeding 10000 people daily through food banks.",
      image:
        "https://images.unsplash.com/photo-1495521821757-a1efb6729352?w=800&q=80",
      goalAmount: 600000 * 100,
      raisedAmount: 360000 * 100,
      category: "Hunger Relief",
      location: "Multi-state",
      organizerName: "Food Bank Foundation",
      organizerEmail: "food@bank.org",
      organizerPhone: "9876543248",
      status: "active",
      featured: true,
      isPublic: true,
      endDate: new Date(Date.now() + 48 * 24 * 60 * 60 * 1000),
    },
    {
      title: "Depression Support Group",
      slug: "depression-support-group",
      description: "Peer support and counseling for people with depression.",
      story: "Creating 30 support groups across major cities.",
      image:
        "https://images.unsplash.com/photo-1577720643272-265f434b0b11?w=800&q=80",
      goalAmount: 400000 * 100,
      raisedAmount: 240000 * 100,
      category: "Mental Health",
      location: "Multi-city",
      organizerName: "Mental Health Alliance",
      organizerEmail: "mental@health.org",
      organizerPhone: "9876543249",
      status: "active",
      featured: false,
      isPublic: true,
      endDate: new Date(Date.now() + 38 * 24 * 60 * 60 * 1000),
    },
    {
      title: "Sanitation Improvement",
      slug: "sanitation-improvement",
      description: "Build toilets and improve sanitation in villages.",
      story: "Constructing 500 public toilets in rural areas.",
      image:
        "https://images.unsplash.com/photo-1584820927498-cfe5211fd63d?w=800&q=80",
      goalAmount: 800000 * 100,
      raisedAmount: 480000 * 100,
      category: "Sanitation",
      location: "Madhya Pradesh",
      organizerName: "Sanitation Trust",
      organizerEmail: "sanitation@trust.org",
      organizerPhone: "9876543250",
      status: "active",
      featured: false,
      isPublic: true,
      endDate: new Date(Date.now() + 55 * 24 * 60 * 60 * 1000),
    },
    {
      title: "Coaching for STEM Subjects",
      slug: "coaching-stem-subjects",
      description:
        "Free coaching for Science, Technology, Engineering, Mathematics.",
      story: "Helping 500 students excel in STEM subjects.",
      image:
        "https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=800&q=80",
      goalAmount: 550000 * 100,
      raisedAmount: 330000 * 100,
      category: "Education",
      location: "Telangana",
      organizerName: "STEM Learning Foundation",
      organizerEmail: "stem@learning.org",
      organizerPhone: "9876543251",
      status: "active",
      featured: true,
      isPublic: true,
      endDate: new Date(Date.now() + 50 * 24 * 60 * 60 * 1000),
    },
    {
      title: "Cancer Screening Drive",
      slug: "cancer-screening-drive",
      description: "Early detection camps for various types of cancer.",
      story: "Free screening for breast, cervical, and oral cancer.",
      image:
        "https://images.unsplash.com/photo-1579154204601-01588f351e67?w=800&q=80",
      goalAmount: 700000 * 100,
      raisedAmount: 420000 * 100,
      category: "Medical",
      location: "Delhi",
      organizerName: "Cancer Awareness Foundation",
      organizerEmail: "cancer@awareness.org",
      organizerPhone: "9876543252",
      status: "active",
      featured: false,
      isPublic: true,
      endDate: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000),
    },
    {
      title: "Slum Upgrade Project",
      slug: "slum-upgrade-project",
      description: "Infrastructure development in slum areas.",
      story: "Improving roads, drainage, and basic amenities.",
      image:
        "https://images.unsplash.com/photo-1517457373614-b7152f800fd1?w=800&q=80",
      goalAmount: 1000000 * 100,
      raisedAmount: 600000 * 100,
      category: "Infrastructure",
      location: "Bangalore",
      organizerName: "Slum Development Foundation",
      organizerEmail: "slum@development.org",
      organizerPhone: "9876543253",
      status: "active",
      featured: true,
      isPublic: true,
      endDate: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000),
    },
    {
      title: "Malaria Prevention Drive",
      slug: "malaria-prevention-drive",
      description: "Mosquito control and malaria awareness campaign.",
      story: "Distribution of mosquito nets and awareness workshops.",
      image:
        "https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?w=800&q=80",
      goalAmount: 400000 * 100,
      raisedAmount: 240000 * 100,
      category: "Health",
      location: "Chhattisgarh",
      organizerName: "Health Prevention Trust",
      organizerEmail: "health@prevention.org",
      organizerPhone: "9876543254",
      status: "active",
      featured: false,
      isPublic: true,
      endDate: new Date(Date.now() + 42 * 24 * 60 * 60 * 1000),
    },
    {
      title: "Baking and Pastry Training",
      slug: "baking-pastry-training",
      description: "Vocational training in baking and pastry making.",
      story: "Empowering 100 women with bakery skills.",
      image:
        "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80",
      goalAmount: 300000 * 100,
      raisedAmount: 180000 * 100,
      category: "Skill Development",
      location: "Gujarat",
      organizerName: "Baking Skills Foundation",
      organizerEmail: "baking@skills.org",
      organizerPhone: "9876543255",
      status: "active",
      featured: false,
      isPublic: true,
      endDate: new Date(Date.now() + 35 * 24 * 60 * 60 * 1000),
    },
    {
      title: "Fishermen Support Initiative",
      slug: "fishermen-support-initiative",
      description: "Improve livelihoods of fishing communities.",
      story: "Providing nets, training, and market access.",
      image:
        "https://images.unsplash.com/photo-1520626353608-84224e7a85d2?w=800&q=80",
      goalAmount: 600000 * 100,
      raisedAmount: 360000 * 100,
      category: "Economic Empowerment",
      location: "Kerala",
      organizerName: "Fishermen Welfare Foundation",
      organizerEmail: "fisher@welfare.org",
      organizerPhone: "9876543256",
      status: "active",
      featured: true,
      isPublic: true,
      endDate: new Date(Date.now() + 50 * 24 * 60 * 60 * 1000),
    },
    {
      title: "Yoga and Wellness",
      slug: "yoga-wellness",
      description: "Yoga classes and wellness programs for communities.",
      story: "Promoting physical and mental health through yoga.",
      image:
        "https://images.unsplash.com/photo-1544367563-12123d8965cd?w=800&q=80",
      goalAmount: 300000 * 100,
      raisedAmount: 180000 * 100,
      category: "Health",
      location: "Goa",
      organizerName: "Wellness Foundation",
      organizerEmail: "wellness@yoga.org",
      organizerPhone: "9876543257",
      status: "active",
      featured: false,
      isPublic: true,
      endDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
    },
  ];

  for (const campaign of campaigns) {
    const userIndex = Math.floor(Math.random() * users.length);
    await prisma.campaign.upsert({
      where: { slug: campaign.slug },
      update: {},
      create: {
        ...campaign,
        userId: users[userIndex].id,
      },
    });
  }
  console.log("✅ Campaigns created:", campaigns.length);

  // Create Volunteers
  const volunteers = [
    {
      name: "Arun Prakash",
      email: "arun.prakash@gmail.com",
      phone: "9812345670",
      address: "Chennai, Tamil Nadu",
      skills: "Teaching, Event Management",
      availability: "Weekends",
      motivation:
        "I want to give back to society and help children get quality education.",
      status: "approved",
    },
    {
      name: "Sneha Kapoor",
      email: "sneha.kapoor@gmail.com",
      phone: "9812345671",
      address: "Mumbai, Maharashtra",
      skills: "Medical Aid, First Aid",
      availability: "Flexible",
      motivation:
        "As a nurse, I want to use my skills to help those who cannot afford healthcare.",
      status: "approved",
    },
  ];

  const existingVolunteers = await prisma.volunteer.findMany({
    select: { userId: true },
  });
  const usedUserIds = new Set(existingVolunteers.map((v) => v.userId));
  const availableUsers = users.filter((u) => !usedUserIds.has(u.id));

  let volIndex = 0;
  for (const vol of volunteers) {
    if (volIndex >= availableUsers.length) break;
    const existing = await prisma.volunteer.findUnique({
      where: { email: vol.email },
    });
    if (!existing) {
      await prisma.volunteer.create({
        data: {
          ...vol,
          userId: availableUsers[volIndex].id,
        },
      });
      volIndex++;
    }
  }
  console.log("✅ Volunteers created:", volIndex);

  // Create Site Settings
  await prisma.siteSettings.upsert({
    where: { id: "default" },
    update: {},
    create: {
      id: "default",
      siteName: "FUNDamental Grow",
      tagline: "Empowering Communities Through Giving",
      description:
        "A crowdfunding platform dedicated to supporting social causes.",
      email: "info@fundamentalgrow.com",
      phone: "+91 9999999999",
      address: "Mumbai, Maharashtra, India",
      heroTitle: "Fund The Future, Change Lives",
      heroSubtitle:
        "Join thousands making a difference. Support causes you care about.",
      footerText: "Made with ❤️ for Humanity",
    },
  });
  console.log("✅ Site settings created");

  console.log("\n🎉 Seed completed!");
  console.log("\n📧 Admin Login:");
  console.log("   Email: admin@fundamentalgrow.com");
  console.log("   Password: admin123");
  console.log("\n📊 Data Summary:");
  console.log("   - Users: " + users.length);
  console.log("   - Campaigns: " + campaigns.length);
  console.log("   - Volunteers: " + volunteers.length);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
